custom/plugins/Shopware-6-Blog-Plugin-master/src/Controller/BlogController.php
<?php declare(strict_types=1);

namespace Sas\BlogModule\Controller;

use Sas\BlogModule\Content\Blog\BlogEntriesEntity;
use Sas\BlogModule\Page\Search\BlogSearchPageLoader;
use Shopware\Core\Content\Cms\Exception\PageNotFoundException;
use Shopware\Core\Content\Cms\SalesChannel\SalesChannelCmsPageLoaderInterface;
use Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface;
use Shopware\Core\Framework\DataAbstractionLayer\Search\Criteria;
use Shopware\Core\Framework\DataAbstractionLayer\Search\Filter\EqualsFilter;
use Shopware\Core\Framework\DataAbstractionLayer\Search\Filter\RangeFilter;
use Shopware\Core\Framework\Routing\Annotation\RouteScope;
use Shopware\Core\Framework\Routing\Exception\MissingRequestParameterException;
use Shopware\Core\System\SalesChannel\SalesChannelContext;
use Shopware\Core\System\SystemConfig\SystemConfigService;
use Shopware\Storefront\Controller\StorefrontController;
use Shopware\Storefront\Framework\Cache\Annotation\HttpCache;
use Shopware\Storefront\Page\GenericPageLoaderInterface;
use Shopware\Storefront\Page\Navigation\NavigationPage;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @RouteScope(scopes={"storefront"})
 */
class BlogController extends StorefrontController
{
    private GenericPageLoaderInterface $genericPageLoader;

    private SalesChannelCmsPageLoaderInterface $cmsPageLoader;

    private SystemConfigService $systemConfigService;

    private EntityRepositoryInterface $blogRepository;

    private BlogSearchPageLoader $blogSearchPageLoader;

    public function __construct(
        SystemConfigService $systemConfigService,
        GenericPageLoaderInterface $genericPageLoader,
        SalesChannelCmsPageLoaderInterface $cmsPageLoader,
        EntityRepositoryInterface $blogRepository,
        BlogSearchPageLoader $blogSearchPageLoader
    ) {
        $this->systemConfigService = $systemConfigService;
        $this->genericPageLoader = $genericPageLoader;
        $this->cmsPageLoader = $cmsPageLoader;
        $this->blogRepository = $blogRepository;
        $this->blogSearchPageLoader = $blogSearchPageLoader;
    }

    /**
     * @HttpCache()
     * @Route("/sas_blog/search", name="sas.frontend.blog.search", methods={"GET"})
     */
    public function search(Request $request, SalesChannelContext $context): Response
    {
        try {
            $page = $this->blogSearchPageLoader->load($request, $context);
        } catch (MissingRequestParameterException $missingRequestParameterException) {
            return $this->forwardToRoute('frontend.home.page');
        }

        return $this->renderStorefront('@Storefront/storefront/page/blog-search/index.html.twig', ['page' => $page]);
    }

    /**
     * @HttpCache()
     * @Route("/widgets/blog-search", name="widgets.blog.search.pagelet", methods={"GET", "POST"}, defaults={"XmlHttpRequest"=true})
     *
     * @throws MissingRequestParameterException
     */
    public function ajax(Request $request, SalesChannelContext $context): Response
    {
        $request->request->set('no-aggregations', true);

        $page = $this->blogSearchPageLoader->load($request, $context);

        $response = $this->renderStorefront('@Storefront/storefront/page/blog-search/search-pagelet.html.twig', ['page' => $page]);
        $response->headers->set('x-robots-tag', 'noindex');

        return $response;
    }

    /**
     * @HttpCache()
     * @Route("/sas_blog/{articleId}", name="sas.frontend.blog.detail", methods={"GET"})
     */
    public function detailAction(string $articleId, Request $request, SalesChannelContext $context): Response
    {
        $page = $this->genericPageLoader->load($request, $context);
        $page = NavigationPage::createFrom($page);

        $criteria = new Criteria([$articleId]);

        $criteria->addAssociations(['blogAuthor.salutation', 'blogCategories']);

        $results = $this->blogRepository->search($criteria, $context->getContext())->getEntities();

        /** @var BlogEntriesEntity $entry */
        $entry = $results->first();

        if (!$entry) {
            throw new PageNotFoundException($articleId);
        }

        $pages = $this->cmsPageLoader->load(
            $request,
            new Criteria([$this->systemConfigService->get('SasBlogModule.config.cmsBlogDetailPage')]),
            $context
        );

        $page->setCmsPage($pages->first());

        if ($metaInformation = $page->getMetaInformation()) {
            $metaTitle = $entry->getMetaTitle() ?? $entry->getTitle();
            $metaDescription = $entry->getMetaDescription() ?? $entry->getTeaser();
            $metaAuthor = $entry->getBlogAuthor()->getTranslated()['name'];
            $metaInformation->setMetaTitle($metaTitle ?? '');
            $metaInformation->setMetaDescription($metaDescription ?? '');
            $metaInformation->setAuthor($metaAuthor ?? '');
            $page->setMetaInformation($metaInformation);
        }

        $page->setNavigationId($page->getHeader()->getNavigation()->getActive()->getId());

        return $this->renderStorefront('@Storefront/storefront/page/content/index.html.twig', [
            'page' => $page,
            'entry' => $entry,
        ]);
    }

    /**
     * @HttpCache()
     * @Route("/blog/rss", name="frontend.sas.blog.rss", methods={"GET"})
     */
    public function rss(Request $request, SalesChannelContext $context): Response
    {
        $criteria = new Criteria();

        $dateTime = new \DateTime();

        $criteria->addAssociations(['blogAuthor.salutation']);

        $criteria->addFilter(
            new EqualsFilter('active', true),
            new RangeFilter('publishedAt', [RangeFilter::LTE => $dateTime->format(\DATE_ATOM)])
        );

        $results = $this->blogRepository->search($criteria, $context->getContext())->getEntities();

        $page = $this->genericPageLoader->load($request, $context);
        $page = NavigationPage::createFrom($page);

        $response = $this->renderStorefront('@SasBlogModule/storefront/page/rss.html.twig', [
            'results' => $results,
            'page' => $page,
        ]);
        $response->headers->set('Content-Type', 'application/xml; charset=utf-8');

        return $response;
    }
}

custom/plugins/Shopware-6-Blog-Plugin-master/src/Controller/StoreApi/BlogController.php
<?php declare(strict_types=1);

namespace Sas\BlogModule\Controller\StoreApi;

use OpenApi\Annotations as OA;
use Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface;
use Shopware\Core\Framework\DataAbstractionLayer\Search\Criteria;
use Shopware\Core\Framework\DataAbstractionLayer\Search\Filter\EqualsFilter;
use Shopware\Core\Framework\Plugin\Exception\DecorationPatternException;
use Shopware\Core\Framework\Routing\Annotation\Entity;
use Shopware\Core\Framework\Routing\Annotation\RouteScope;
use Shopware\Core\Framework\Uuid\Uuid;
use Shopware\Core\System\SalesChannel\SalesChannelContext;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @RouteScope(scopes={"store-api"})
 */
class BlogController extends AbstractBlogController
{
    /**
     * @var EntityRepositoryInterface
     */
    private $blogRepository;

    public function __construct(EntityRepositoryInterface $blogRepository)
    {
        $this->blogRepository = $blogRepository;
    }

    public function getDecorated(): AbstractBlogController
    {
        throw new DecorationPatternException(self::class);
    }

    /**
     * @Entity("sas_blog_entries")
     * @OA\Get(
     *      path="/store-api/blog",
     *      summary="This route can be used to load the sas_blog_entries by specific filters",
     *      operationId="listBlog",
     *      tags={"Store API", "Blog"},
     *      @OA\Parameter(name="Api-Basic-Parameters"),
     *      @OA\Response(
     *          response="200",
     *          description="",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(
     *                  property="total",
     *                  type="integer",
     *                  description="Total amount"
     *              ),
     *              @OA\Property(
     *                  property="aggregations",
     *                  type="object",
     *                  description="aggregation result"
     *              ),
     *              @OA\Property(
     *                  property="elements",
     *                  type="array",
     *                  @OA\Items(ref="#/components/schemas/blog_entities_flat")
     *              )
     *          )
     *     )
     * )
     * @Route("/store-api/blog", name="store-api.sas.blog.load", methods={"GET","POST"})
     */
    public function load(Request $request, Criteria $criteria, SalesChannelContext $context): BlogControllerResponse
    {
        $criteria = $this->buildCriteria($request, $criteria);

        return new BlogControllerResponse($this->blogRepository->search($criteria, $context->getContext()));
    }

    protected function buildCriteria(Request $request, Criteria $criteria): Criteria
    {
        $search = $request->get('search');
        if ($search) {
            if (Uuid::isValid($search)) {
                $criteria->setIds([$search]);
            } else {
                $criteria->addFilter(new EqualsFilter('slug', $search));
            }
        }

        $criteria->addAssociations(['blogAuthor.salutation', 'blogCategories']);

        return $criteria;
    }
}

custom/plugins/Shopware-6-Blog-Plugin-master/src/Controller/StoreApi/BlogControllerResponse.php
<?php declare(strict_types=1);

namespace Sas\BlogModule\Controller\StoreApi;

use Sas\BlogModule\Content\Blog\BlogEntriesCollection;
use Shopware\Core\Framework\DataAbstractionLayer\Search\EntitySearchResult;
use Shopware\Core\System\SalesChannel\StoreApiResponse;

class BlogControllerResponse extends StoreApiResponse
{
    /**
     * @var EntitySearchResult
     */
    protected $object;

    public function __construct(EntitySearchResult $object)
    {
        parent::__construct($object);
    }

    public function getBlogEntries(): BlogEntriesCollection
    {
        /** @var BlogEntriesCollection $collection */
        $collection = $this->object->getEntities();

        return $collection;
    }
}

custom/plugins/Shopware-6-Blog-Plugin-master/src/Resources/views/storefront/component/blog/card/box.html.twig
{% block sas_blog_card %}
    <article class="card blog-card">
        {% block sas_blog_card_teaser_image %}
            <a href="{{ seoUrl('sas.frontend.blog.detail', {'articleId': article.id}) }}"
                   title="{{ article.translated.title }}"
                   class="blog-image-link">
                    {% if article.media.url %}
                        {% set attributes = {
                            'class': 'blog-image card-img-top',
                            'alt': (article.media.translated.alt ?: article.media.fileName),
                            'title': (article.media.translated.title ?: article.media.fileName)
                        } %}

                        {% sw_thumbnails 'blog-image-thumbnails' with {
                            media: article.media,
                            sizes: {
                                'xs': '330px',
                                'lg': '650px'
                            }
                        } %}
                    {% else %}
                        <div class="blog-image-placeholder">
                            {% sw_icon 'placeholder' style {
                                'size': 'fluid'
                            } %}
                        </div>
                    {% endif %}
                </a>
        {% endblock %}
        {% block sas_blog_card_body %}
            <div class="card-body">
                <div class="d-flex flex-column">
                    {% block sas_blog_card_title_date %}
                        <p class="mt-2 mb-1 d-flex align-items-center blog-date">
                            <small>{{ article.publishedAt|format_date('short', locale=app.request.locale) }}</small>
                        </p>
                    {% endblock %}
                    {% block sas_blog_card_title %}
                        <h2 class="card-title mt-0">
                            {% block sas_blog_card_title_link %}
                                <a href="{{ seoUrl('sas.frontend.blog.detail', { articleId: article.id }) }}"
                                   title="{{ article.translated.title }}"
                                   class="text-decoration-none">
                                    {{ article.translated.title }}
                                </a>
                            {% endblock %}
                        </h2>
                    {% endblock %}
                </div>
                {% block sas_blog_card_teaser %}
                    <p class="card-text font-size-small mb-0">{{ article.translated.teaser }}</p>
                {% endblock %}
            </div>
        {% endblock %}

        {% block sas_blog_card_footer %}
        <div class="card-footer text-muted">
            {% block sas_blog_card_footer_author %}
                {% if config('SasBlogModule').config.showAuthor %}
                    {% if article.blogAuthor.media.url %}
                        {% set attributes = {
                            'class': 'blog-author-avatar',
                            'alt': (article.blogAuthor.media.translated.alt ?: article.blogAuthor.media.fileName),
                            'title': (article.blogAuthor.media.translated.title ?: article.blogAuthor.media.fileName)
                        } %}

                        {% sw_thumbnails 'blog-author-avatar-thumbnails' with {
                            media: article.blogAuthor.media,
                            sizes: {
                            'xs': '80px'
                        }
                            } %}
                    {% else %}
                        <div class="blog-image-placeholder">
                            {% sw_icon 'placeholder' style {
                                'size': 'fluid'
                                } %}
                        </div>
                    {% endif %}
                    <p class="blog-author-display-name">{{ article.blogAuthor.displayName }}<br>
                        <small class="text-muted">{{ article.blogAuthor.blogEntries|length }} {{ 'sas-blog.box.author.countEntries'|trans|sw_sanitize }}</small>
                    </p>
                {% endif %}
            {% endblock %}
        </div>
        {% endblock %}
    </article>
{% endblock %}